### ISSUE TITLE
Sorting and filtering don't work for the default calendar page

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-mocca-calendar#10]
Please see the following [JIRA](https://jira.xwiki.org/browse/MOCCACAL-115) issue.

**Comment by CamiAndrei** [comment]
This is invalid. Sorting and filtering works well. The only thing that make this confusing, is  the "Other Events" that is displayed when filter by the word "calendar" . 
![Screenshot from 2019-10-17 10-23-53](https://user-images.githubusercontent.com/12369283/66987086-bc9c5c00-f0c8-11e9-8276-a97aab75e629.png)
![Screenshot from 2019-10-17 10-27-18](https://user-images.githubusercontent.com/12369283/66987083-bc9c5c00-f0c8-11e9-9c48-8bb0fef6a61b.png)

**Comment by lucaa** [comment]
This _is_ a valid issue, the calendars in the list do not respect the alphabetical order when sorted (the item starting with A is in the middle, between an O and  C, so there _is_ an issue there ) :
![image](https://user-images.githubusercontent.com/657716/100268962-1de26000-2f56-11eb-8fe1-05e4fa6a6e8c.png)

However, as commented on the original issue this problem results from the fact that "Other events" has a computed title, and it's a "classical" xwiki problem.
In 12.6.4 version at least, there is a message displayed on the bottom of the livetable warning about the bad filtering and sorting, so we could consider this problem to not need a fix that is specific to the application and close the ticket (at least for XWiki versions for which this message is displayed).

**Comment by lucaa** [comment]
Apparently the warning for computed titles was added in http://jira.xwiki.org/browse/XWIKI-14647 , version 10.9 of XWiki. So I guess this issue is still not fixed for all the versions supported by the calendar application, we should probably leave it open until the minimum compat version is raised, or close it as a "won't fix" on the application.

**Comment by ClemensRobbenhaar** [comment]
It seems the currently supported minimal platform version is 11.10. Can this issue be closed then?
