### ISSUE TITLE
Calendar template is not preselected when creating a new entry

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-mocca-calendar#18]
STEPS TO REPRODUCE

1. Go to Calendar Pro homepage
2. Click on the "Create" button to create a new entry

EXPECTED RESULTS

Calendar template is selected.

ACTUAL RESULTS

'Blank page' is selected instead.

![default_blank](https://user-images.githubusercontent.com/32512703/48336502-1b5f8700-e669-11e8-8dd1-2b993a855a2a.jpg)

**Comment by oanalavinia** [comment]
I reopened it since this is still reproducing for older versions of xwiki then 9.5
