### ISSUE TITLE
Using the {{moccacalendar/}} macro breaks the JavaScript on the page

### ISSUE THREAD

**Issue by evalica** [xwikisas/application-mocca-calendar#29]
-  Install "Calendar Application (Pro)"
-  I didn't complete the license step
-  Go to a page and from the editor add the "Mocca Calendar" macro
-  Or just use it from the wiki syntax `{{moccacalendar/}`}
- On the page where it was added:
  -  the drawer stops functioning; 
  -  the search suggest doesn't work;
  -  notifications event won't load, etc;

From an usability POV this issue is critical since using this macro prevents navigation.
Chrome Console: 
```
(index):689 Uncaught TypeError: Cannot read property 'Helper' of undefined
    at HTMLDocument.<anonymous> ((index):689)
    at i (jquery.js:3187)
    at Object.fireWith [as resolveWith] (jquery.js:3317)
    at ready (jquery.js:3536)
```
<img width="1189" alt="bug" src="https://user-images.githubusercontent.com/629552/60341793-588a4680-99b8-11e9-8ef6-6184fd7b376b.png">

Firefox console:
```
TypeError: XWiki.MoccaCalendar is undefined Test:542:19
```

Tested with XWiki 11.5, Calendar Pro 2.8.4, Chrome 75 and Firefox Dev 68 on Mac.

**Comment by CamiAndrei** [comment]
This issue has been fixed by the commit from #28 .
