### ISSUE TITLE
End dates cannot be selected anymore if a date before the Start date was selected first

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-mocca-calendar#35]
STEPS TO REPRODUCE

1. Go to Calendar Pro App
2. Click 'Create new event'
3. Set a title
3. Set a Start date (for ex. 'Now')
4. Set an End date **before** the Start date (e.g. 3 days earlier)
5. Click 'Save'
6. After the 'End date must be after start date.' warning, click again on 'End Date' field
7. Choose any other date (from past or future) by clicking on it

EXPECTED RESULTS

A new date can be selected properly.

ACTUAL RESULTS

Even if the date is clicked on the picker, no date is being selected at all in the field. Moreover, the warning 'End date must be after start date.' is still present regardless if the new chosen date is after the start date.

The only way to fill the end date at this point is to input it manually.

Environment: Windows 10 Pro 64 bit, Chrome 78, using a local instance XWiki 11.10 on PostgreSQL 12, Calendar Pro 2.8.8

![End_date_not_selected](https://user-images.githubusercontent.com/32512703/70321233-772a1e80-182f-11ea-8fad-49076798154f.jpg)

**Comment by snazare** [comment]
not reproducing on XWiki 15.10.10, Calendar Application Pro 2.13.3.
