### ISSUE TITLE
Event name doesn't respect the naming strategy set at wiki level

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-mocca-calendar#43]
Preconditions: Set up the [Preformatted Names Strategy](https://extensions.xwiki.org/xwiki/bin/view/Extension/Name%20Strategies%20Module/#HPreformattedNamesStrategy) first:

1. Login as Admin
2. Go to Administer Wiki > Editing > Name Strategies
3. Under 'Current Name Strategy' select 'Preformatted names (no accents, no space, no special characters)'
4. Under 'Transform name automatically' select 'Enabled'
5. Under 'Validate names before saving' select 'Disabled'
6. Click 'Save'

Steps to reproduce:

1. Click on Calendar from Applications
2. Click on Create new event
3. Fill all the information needed, in the Title section add some text which includes some accents, spaces and special characters in its name (e.g. Té£  / stΦéd OR There are 5 French accents: the cédille Ç, the accent aigu é, the accent circonflexe â, ê, î, ô, û, the accent grave à, è, ù and the accent tréma ë, ï, ü OR The umlaut (ä, ë, ï, ö, ü) is the only accent used in German writing.)
4. Click on Save

Expected results: 

1. The entry is saved and can be seen the Calendar.
2. The title with the accents, spaces and special characters is updated in the URL accordingly to the naming strategy - the Event can be selected from the breadcrumb.

Actual results: The event is saved properly but the name is not transformed in the URL.

![EventURL](https://user-images.githubusercontent.com/40691112/93913626-05fc1f00-fd0e-11ea-847c-f7568c95868d.jpg)

**Comment by lucaa** [comment]
Updated the title of the ticket to mark properly that it's the **name** of the item that needs to respect the naming stragegy, not the title . The naming strategy has no impact on titles and there is no feature in XWiki intervening on page titles.
