### ISSUE TITLE
The color pickers don't open anymore

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-mocca-calendar#45]
Environment: Windows 10 Pro 64 bit, Firefox 83, using a local instance XWiki 12.9 on Oracle 19c, Calendar Pro 2.9

STEPS TO REPRODUCE

1. Go to Calendar Pro App
2. Click 'Create new calendar'
3. Set a title
4. Click 'Create'
5. Click on color pickers from 'Background color of entries in the calendar view' field or 'Text color of entries in the calendar view'

EXPECTED RESULTS

The picker opens in order for a color to be chosen.

ACTUAL RESULTS

Nothing happens. In browser's console (Firefox 83) there is the following error:

```
Uncaught ReferenceError: assignment to undeclared variable source
 
update procolor.js:701
    createDiv procolor.js:489
    initialize procolor.js:364
    k prototype.js:82
    toggle procolor.js:1635
    eventHandler procolor.js:1712
    setTimeout handler*eventHandler procolor.js:1712
    bindAsEventListener prototype.js:419
    _createResponder prototype.js:7276
    u prototype.js:7023
    attachButton procolor.js:1580
    <anonymous> procolor.js:1744
    each prototype.js:859
    <anonymous> procolor.js:1743
    _createResponder prototype.js:7276
    u prototype.js:7023
    <anonymous> procolor.js:1742
```

![Calendar_color_picker_Firefox_error](https://user-images.githubusercontent.com/32512703/99529272-2fe95f00-29a8-11eb-8be3-5894970b3c68.png)

**Comment by acotiuga** [comment]
This cannot be reproduced in XWiki 12.6, with the latest Calendar version. Further investigation is needed on XWiki 12.9 to see the problem. It may not be related to this application.

**Comment by acotiuga** [comment]
Reported https://jira.xwiki.org/browse/XWIKI-18106 as regression.
