### ISSUE TITLE
Title should not be displayed on the calendar page in view mode, neither should "Content"

### ISSUE THREAD

**Issue by lucaa** [xwikisas/application-mocca-calendar#48]
Currently, on the calendar page, in view mode, the title of the calendar is repeated - it's already displayed as page title. That field is useful in edit mode, for users to be able to update document title, but not in view mode.

![image](https://user-images.githubusercontent.com/657716/99558947-8b294a80-29c4-11eb-8c8f-dd60b1e046ad.png)

Also, a label "Content" seems to be displayed, which is not exactly clear what is labeling... is it the display of the calendar itself? If so, it's not very clear and it's also not very useful... We probably should compact this metadata section as much as possible on the calendar page, the most important is the calendar itself...

**Comment by acotiuga** [comment]
Since the colours don't bring any value to the viewer, I would not display them either in view mode. It is clear in the calendar what is the colour scheme and the calendar description can be displayed without the `DESCRIPTION` label.

**Comment by acotiuga** [comment]
This is the new calendar layout in view mode:
![calendarAfter](https://user-images.githubusercontent.com/8121819/99990469-81d12100-2dbc-11eb-81c0-1d214d665b48.png)

**Comment by lucaa** [comment]
> Since the colours don't bring any value to the viewer, I would not display them either in view mode. It is clear in the calendar what is the colour scheme and the calendar description can be displayed without the DESCRIPTION label.

The colors do bring value in view mode: If the calendar has no events  (in the current view) they show the actual color and they also show that that color is configurable (otherwise it's not at all clear, before hitting the edit button, that the colors of the calendar are configurable per calendar and not just random colors from the system).

If the calendar has no events  (in the current view) = the user should not be expected to navigate backwards and forward in time in the calendar in order to find one valid event - if it exists - in order to "discover" the colors used for this calendar on the screen, especially if they don't have edit right and can't just hit "edit" to see what the edit mode displays.

As a principle, I think it's quite counter intuitive that metadata is hidden from a user in view mode and displayed in edit mode, especially metadata that is already filled in, but also for empty values. First, because when a user with edit right changes that data they need to see feedback on the screen, upon save, that the change was saved: if the values are not displayed, that feedback does not exist, they save but they don't necessarily see a confirmation that the save was performed. Then, because it's easier to discover the structure of an element and understand how to operate with it if they see the description of the element in view mode (the fact that a metadata exists and can be set is part of the description of an item).

Also, I have some doubts about displaying the description without label (the question is for anything without label) but I guess that could work, it's indeed quite obvious what it is and it has the label in edit mode.

When I was talking about compacting the section, I didn't mean to remove data from it but maybe display it on 2 columns (or otherwise) to take less vertical space. For example, background and foreground colors can be easily compacted in a smaller display that takes less space (the easiest is to display it on 2 columns, a more elaborate one would be to just display the foreground color on the background color or something, but we don't need it for now).
