### ISSUE TITLE
Event date pickers are broken since XWiki 12.7

### ISSUE THREAD

**Issue by acotiuga** [xwikisas/application-mocca-calendar#50]
Similar to #45, some changes in XWiki 12.7 affected the javascript libraries or the way they are used.
One option is to investigate and report a regression on https://jira.xwiki.org.
The other one is to update the pickers (color and date) and use the new approach from the XWiki Standard, since some reusable pickers were implemented as macros. See https://www.xwiki.org/xwiki/bin/view/Documentation/DevGuide/FrontendResources/Pickers/ for the full list of pickers.

**Comment by acotiuga** [comment]
Reported https://jira.xwiki.org/browse/XWIKI-18106 as regression. See https://jira.xwiki.org/browse/XWIKI-18106?focusedCommentId=107566&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-107566

**Comment by acotiuga** [comment]
This is fixed in XWiki 12.10.1 as per https://jira.xwiki.org/browse/XWIKI-18106

**Comment by lucaa** [comment]
> [...] update the pickers (color and date) and use the new approach from the XWiki Standard, since some reusable pickers were implemented as macros. See https://www.xwiki.org/xwiki/bin/view/Documentation/DevGuide/FrontendResources/Pickers/ for the full list of pickers.

Shouldn't this be done, nevertheless, for consistency reasons and also for avoiding a dependency on something that is less API than a "standard" picker?
