### ISSUE TITLE
Allow to show meetings in the calendar

### ISSUE THREAD

**Issue by ClemensRobbenhaar** [xwikisas/application-mocca-calendar#67]
The Calendar Application should display also all the meetings from the Meetings Application.

Must have:

- optionally allow to show meetings in the calendar
- show the meetings in the date range used by the current calendar
- limit the range of meeting details shown in a way "reasonable" for the current calendar.
- allow to access details of every meeting from the calendar (at least via link to the meeting details page)

- does not break if the meetings application is not installed

Should have:

- optionally limit the meetings shown in a calendar to the ones in a given (different) space
- ability to move meetings in the calendar
- ability to edit meetings in the calendar

**Comment by mflorea** [comment]
Fixed with 32b3bb46bfb2585974d383a9b1bc9518828178e6, 94a524bd35540c4689083af4f04338248708cf99 and d2fe7b1ed4446fa3bec0d611992b51d89029da53 .

**Comment by lucaa** [comment]
> Fixed with [32b3bb4](https://github.com/xwikisas/application-mocca-calendar/commit/32b3bb46bfb2585974d383a9b1bc9518828178e6), [94a524b](https://github.com/xwikisas/application-mocca-calendar/commit/94a524bd35540c4689083af4f04338248708cf99) and [d2fe7b1](https://github.com/xwikisas/application-mocca-calendar/commit/d2fe7b1ed4446fa3bec0d611992b51d89029da53) .

A bunch of (other) commits were done for this ticket and tagged with #47, so if all commits for this work need to be discovered, that issue is a good source of information.
