### ISSUE TITLE
Past/Future events aren't showing in Agenda, UI looks broken

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-mocca-calendar#68]
Issue seems to be related to https://github.com/xwikisas/application-mocca-calendar/issues/42

Steps to reproduce:

1. Create some events in the past, present and in the future on the same or different calendars 
![CalendarWithEvents](https://user-images.githubusercontent.com/40691112/141781508-45e6fdd2-7509-486a-82b1-d45d99efdd39.jpg)
2. Click on the "Agenda" tag 
![AgendaToday](https://user-images.githubusercontent.com/40691112/141781546-e572d2a3-c216-4728-bd50-5a8cdfa240a9.jpg)
3. Click on the previous and next buttons 
![PastPresentEvents](https://user-images.githubusercontent.com/40691112/141781567-66b74baf-07c3-44aa-aed0-d86d7f3f54ee.jpg)

Expected results: The UI of the Agenda view shows all the necessary information to the user with a vertical line of the background color used for that calendar. The past / present and future events are shown in the respective selection. 

Actual results:

1. When clicking on Agenda the UI seems to be broken - no vertical line appears, the title on the Present and Future events are shown on the same line with no brake.
![AgendaViewEvents](https://user-images.githubusercontent.com/40691112/141783420-fdbe7818-1d07-4c8b-a24f-b747d7eff8a7.jpg)

2. When clicking on the Past/Future arrows nothing changes, the same view as point 1 remains. The past events aren't shown at all.

Environment: Windows 10, XWiki 12.5.1 with MySQL 8.0 and IE 11, Firefox 94, Edge and Chrome 95, Calendar Application (Pro) 2.10.1

**Comment by ClemensRobbenhaar** [comment]
This should be fixed via the fix for  #74
