### ISSUE TITLE
The "Agenda" view only displays events that are planned for the next day

### ISSUE THREAD

**Issue by aubincleme** [xwikisas/application-mocca-calendar#72]
Initially, the "Agenda" view displayed every event planned for the next 10 years, see https://github.com/xwikisas/application-mocca-calendar/blob/e6c0926ed40de225c8a56c9899a91d43217ce06c/application-mocca-calendar-ui/src/main/resources/MoccaCalendar/Macro.xml#L579

It seems that following an update of FullCalendar, this duration is not taken into account, and thus the Agenda view is falling back on the default of Full Calendar, which is to fetch events for a time span of 1 day in the future.

**Comment by ClemensRobbenhaar** [comment]
I have updated this in upstream, but it was not very easy and the current upstream version has uncovered quite a few more bugs. How urgent is the issue?

**Comment by ClemensRobbenhaar** [comment]
Well, there were more bugs in the current state anyway, so I merged the upstream version manually anyway. Fixed via #75.
