### ISSUE TITLE
All events are present in Agenda view

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-mocca-calendar#75]
Preconditions: Have some events already created in the calendar past/present/future

Steps to reproduce:

1. Access the Calendar 
![EventsInMonthView](https://user-images.githubusercontent.com/40691112/146226602-c997b41a-04a4-4089-95a2-6cc56d1c8864.jpg)

2. Click on Agenda view 
![PastEvents](https://user-images.githubusercontent.com/40691112/146226642-f6356424-8da2-42d8-a2d9-2959b96cd343.jpg)

Expected results: The upcoming events are shown

Actual results: All events are show, including past events. It appears that the Agenda is showing all the events that appear when in Month view e.g. if the user selects November then all the events shown in the Month view are also shown in agenda.

Environment: Windows 10, XWiki 13.10  with MySQL 8.0 and XWiki 13.4.5, Calendar Application (Pro) 2.11-rc-1

**Comment by ClemensRobbenhaar** [comment]
This should be fixed now in the same commit that fixed #74
