### ISSUE TITLE
Cannot save new calendar page

### ISSUE THREAD

**Issue by ClemensRobbenhaar** [xwikisas/application-mocca-calendar#78]
Precondition: the meetings app is installed, too, and the calendar app is configured to show meetings on the calendars (Administer Wiki > Other > Calendar).

Steps to reproduce:
1. got to the calendar overview
2. choose "Create new Calendar"
3. pick a title on the following page and "create"
4. the following page shows the new page in edit mode, including a "Configure events from source «Meetings»" section
5. Press "save & view"

Expected result:  see the new calendar in view mode
Actual result: Error message that the server does not respond on save.

The issue was fixed together with the commit https://github.com/xwikisas/application-mocca-calendar/commit/4648726756aa9dfe8c0c9924a652c1c1f6da2ee9 for #77   but as not all testing instances are updated, it confused people if it is fixed or still around.

The issue is definitely present in 2.11-rc-1. The next release should fix it.

![SimpleCalendar](https://user-images.githubusercontent.com/4411046/146773046-10d79dbc-62d8-484d-8186-d6fae3009256.jpg)

**Comment by mflorea** [comment]
Seems to work fine in 2.11.1
