### ISSUE TITLE
Sort out translation pages

### ISSUE THREAD

**Issue by slauriere** [xwikisas/application-mocca-calendar#91]
The app contains currently two translation pages: `MoccaCalendarTranslations` and `MoccaCalendarMacroTranslations`. The commit f206ec85 removed page `MoccaCalendarMacroTranslations` and moved its entries to `MoccaCalendarTranslations`, however:
- This change was not performed in the contrib app.
- The subsequent commit 47d363d4 merged `MoccaCalendarMacroTranslations` in languages es,fr,sk without restoring the page in the default language.
 
This issue is about restoring translation pages consistency.

**Comment by slauriere** [comment]
Maybe we should:
- Remove `MoccaCalendarMacroTranslations` in es,fr,sk from the xwikisas repository.
- Update the contrib repository by moving all entries in `MoccaCalendarMacroTranslations` to `MoccaCalendarTranslations` so that the translation pages remain synchronizable between the contrib and xwikisas repositories.

What do you think @ClemensRobbenhaar, @mflorea, all?

**Comment by ClemensRobbenhaar** [comment]
The existence of the `MoccaCalendarMacroTranslations` page has been an early mistake from my side.
If this can be corrected without creating too much hassle to the infrastructure and/or upgrades, that would be great.

**Comment by slauriere** [comment]
Thank you @ClemensRobbenhaar. I created #92 along this line and [MOCCACAL-149](https://jira.xwiki.org/browse/MOCCACAL-149) in the contrib project with a pull request for it: xwiki-contrib/application-mocca-calendar#30.
